#!/usr/bin/env node
'use strict';

const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

const rootDir = '.';

// update version
function makeCachebuster(template, output) {
	let indexContents = fs.readFileSync(path.resolve(rootDir, template), {encoding: 'utf8'});

	// add hashes to js and css files
	process.stdout.write("Updating hashes... ");
	indexContents = indexContents.replace(/(src|href)="\.\/(.*?)\?[a-z0-9]*?"/g, function (a, b, c) {
		let hash = Math.random(); // just in case creating the hash fails
		try {
			const filename = c.replace('//play.pokemonshowdown.com/', '../../play.pokemonshowdown.com/');
			const fstr = fs.readFileSync(path.resolve(rootDir, 'dist', filename), 'utf8');
			hash = crypto.createHash('md5').update(fstr).digest('hex').substr(0, 8);
		} catch (e) {}

		return b + '="./' + c + '?' + hash + '"';
	}).replace(/\.template\.html/g, '.html');
	process.stdout.write("Writing new `" + output + "` file... ");
	fs.writeFileSync(path.resolve(rootDir, output), indexContents);
	console.log("DONE");
}

function makeRRVersionPage(versionId, label, gen) {
	const template = 'dist/index.template.html';
	const outputTemplate = `dist/${versionId}.template.html`;
	let contents = fs.readFileSync(path.resolve(rootDir, template), {encoding: 'utf8'});
	contents = contents
		.replace(
			/Pok&eacute;mon Radical Red Damage Calculator/g,
			`Pok&eacute;mon Radical Red ${label} Damage Calculator`
		)
		.replace(/rrcalc\/current-/g, `rrcalc/${versionId}-`)
		.replace(/value="9" id="gen9" checked="checked"/g, `value="${gen}" id="gen${gen}" checked="checked"`);
	fs.writeFileSync(path.resolve(rootDir, outputTemplate), contents);
	makeCachebuster(outputTemplate, `dist/${versionId}.html`);
}

function cpdir(src, dest) {
	console.log("Copying `" + src + "` to `" + dest + "`");
	try {
		fs.mkdirSync(dest, '0755');
	} catch(e) {
		if (e.code != 'EEXIST') throw e;
	}
	for (const file of fs.readdirSync(src)) {
		var current = fs.lstatSync(path.join(src, file));
		if (current.isDirectory()) {
			cpdir(path.join(src, file), path.join(dest, file));
		} else if (current.isSymbolicLink()) {
			var symlink = fs.readlinkSync(path.join(src, file));
			fs.symlinkSync(symlink, path.join(dest, file));
		} else if (file.endsWith('.js')) {
			let contents = fs.readFileSync(path.join(src, file), 'utf8').replace(/^exports.* = void 0;$/gm, '');
			// Minify the sets so we save bandwith
			if (src === 'src/js/data/sets') {
				const brkOpenIdx = contents.indexOf('{');
				contents = `${contents.slice(0, brkOpenIdx)}${JSON.stringify(JSON.parse(contents.slice(brkOpenIdx, -2)))};`
			}
			fs.writeFileSync(path.join(dest, file), contents);
		} else {
			const srcFile = path.join(src, file);
			const destFile = path.join(dest, file);
			try {
				fs.copyFileSync(srcFile, destFile);
			} catch (e) {
				if (!['EACCES', 'EPERM'].includes(e.code) || !fs.existsSync(destFile)) throw e;
				const srcStat = fs.statSync(srcFile);
				const destStat = fs.statSync(destFile);
				if (srcStat.size !== destStat.size) throw e;
				console.warn("Skipping locked unchanged file `" + destFile + "`");
			}
		}
	}
}

if (process.argv[2] !== 'view') {
	require('child_process').execSync('npm --prefix calc/ run compile', {stdio: 'inherit'});
}

cpdir('src', 'dist');
cpdir('calc/dist', 'dist/calc');
makeCachebuster('dist/honkalculate.template.html', 'dist/honkalculate.html');
makeCachebuster('dist/index.template.html', 'dist/index.html');
makeCachebuster('dist/randoms.template.html', 'dist/randoms.html');
makeCachebuster('dist/normal.template.html', 'dist/normal.html');
makeCachebuster('dist/hardcore.template.html', 'dist/hardcore.html');
makeRRVersionPage('rr40', '4.0', 9);
makeRRVersionPage('rr31', '3.1', 8);
makeRRVersionPage('rr23', '2.3', 8);
